[package]
name = "tartivy"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.7"
stable_deref_trait = "1.2.0"
tantivy = "0.24.2"
tar = "0.4.44"
thiserror = "2.0.12"
tracing = "0.1.41"

[dev-dependencies]
tempdir = "0.3.7"
tempfile = "3.20.0"
